name: CD-DEV

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clean And Build With Gradle
        run: ./gradlew clean bootJar

  push-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_DEV_IMAGE }} .
          docker push ${{ secrets.DOCKER_DEV_IMAGE }}

  deploy:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USERNAME }}
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/compose
            sudo docker compose down
            sudo touch .env
            echo "${{ secrets.ENV_FILE }}" | sudo tee .env > /dev/null
            sudo touch docker-compose.yaml
            echo "${{ secrets.DOCKER_DEV_COMPOSE }}" | sudo tee docker-compose.yml > /dev/null
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_DEV_IMAGE }}
            sudo docker compose -f docker-compose.yml --env-file ./.env up -d
            sudo docker image prune -f
